# Generated by Django 3.1.6 on 2021-02-23 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.FloatField(verbose_name='Price')),
                ('status', models.CharField(choices=[('public', 'Published'), ('draft', 'Draft')], default='public', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=255, upload_to='user_image', verbose_name='file')),
                ('title', models.TextField(null=True, verbose_name='Title')),
                ('status', models.CharField(choices=[('public', 'Published'), ('draft', 'Draft')], default='public', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermedia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'User media',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, max_length=255, upload_to='user_image', verbose_name='Image')),
                ('about_text', models.TextField(blank=True, null=True, verbose_name='About text')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('insta', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('whats', models.CharField(blank=True, max_length=255, verbose_name='Whats App')),
                ('geo', models.TextField(blank=True, null=True, verbose_name='Map url from Yandex.Maps')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User info',
                'verbose_name_plural': 'Info',
            },
        ),
    ]
