# Generated by Django 3.1.6 on 2021-03-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User info', 'verbose_name_plural': 'User info'},
        ),
    ]
