lang_dict = {
    'site_title': 'Запись к стоматологу',
    'sign_up_success': 'Вы успешно зарегистрировались, теперь можете войти в свой аккаунт',
    'invalid_err': 'Ошибка валидации!',
    'common_title': 'Введите название',
    'price_title': 'Введите цену',
    'about_text': 'Немного о себе',
    'enter_address': 'Введите рабочий адрес',
    'enter_insta': 'Введите ссылку на ваш Instagram',
    'enter_phone': 'Введите номер теелфона',
    'enter_whats': 'Введите номер WhatsApp',
    'enter_geo': 'Введите ссылку с Яндекс Карт',
    'success_created': 'Успешно создано',
    'success_updated': 'Успешно обновлено',
    'success_deleted': 'Успешно удалено',
    'line_created': 'Запись успешно создана',
    'line_updated': 'Запись успешно обновлена',
    'line_deleted': 'Запись успешно удалена',
    'db_err': 'Ошибка базы данных!',
    'permission_denied': 'В доступе отказано!',
}